## Paste Ruff config below existing pyproject.toml, if one exists
#  (i.e. a Poetry project)

...

[tool.ruff]
## Enable pycodestyle ("E") and Pyflakes ("F") codes by default
select = ["E", "F"]
ignore = []

## Allow autofix for all enabled rules (when "--fix") is provided.
#  NOTE: Leaving these commented until I know what they do
# fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
# unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    "__pycache__",
    "*.pyc"
]
per-file-ignores = {}

## Same as Black.
line-length = 88

## Allow unused variables when underscore-prefixed.
# dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

## Set assumed Python version
target-version = "py310"

[tool.ruff.mccabe]
max-complexity = 10


